# Site Settings
title: "Fabian Veider"
description: "Exploring Computational Social Sciences, Politics and Beatboxing"
theme: jekyll-theme-cayman
custom_css: style.css

# Collections Settings
collections:
  blog:
    output: true

# Markdown Settings
markdown: kramdown
highlighter: rouge

