# Site Settings
title: "Understanding social complexity"
description: "Exploring Computational Social Sciences and Politics. And Beatboxing"
theme: jekyll-theme-cayman
custom_css: style.css

# Collections Settings
collections:
  blog:
    output: true

# Markdown Settings
markdown: kramdown
highlighter: rouge

