# Site Settings
title: "Understanding Social Complexity"
description: "Exploring Computational Social Sciences and Politics. And Beatboxing"
theme: minima
custom_css: style.css

# Appearance
minima:
  skins:
    - black_and_white

# Collections Settings
collections:
  blog:
    output: true

# Markdown Settings
markdown: kramdown
highlighter: rouge

